const northminprojects = [
    {
      leadUnit: "SD-ISE",
      projectNo: "1",
      projectTitle: "Paving the Roads to SDGs through Good Local Governance",
      startDate: "February 2018",
      endDate: "February 2021",
      amount: "c/o external partner",
      partnerFunder: "United Nations Development Programme, DILG-X, Safer River Life Saver Foundation (GHUBS Lead), USTP, Balay Mindanaw",
      principalProponent: "Dexter S. Lo",
      projectBeneficiary:
        "Region X PLGUs:-Bukidnon, Camiguin, Lanao del Norte, Misamis Occidental, Misamis Oriental",
        tappedXUPersonnel: "Abuzo, Anabel A (COE), Arquiza, JCVincent (COE), Baliwag, Therese (SD-ISE), Lo, Dexter (SD-ISE), Sabal, Jhon Louie (CAS)",
        statusRemarks: "completed",
    },
    {
        leadUnit: "CGH",
        projectNo: "2",
        projectTitle: "Integrated Water, Sanitation and Hygien (iWASH) Hub for the Implementation of SAgana at LIgtas na Tubig Para sa Lahat (SALINTUBIG) Project",
        startDate: "September 2017",
        endDate: "2022",
        amount: "UNDP:Php 349,280.00 || DILG (SALINTUBIG):Php 2,274,000.00",
        partnerFunder: "DILG-Region X, Cagayan de Oro Water District, Malaybalay City Water District, Safer River Life Saver Foundation, Inc, Seway Inc, Group Foundation",
        principalProponent: "as of SY 2020: Gina S. Itchon",
        projectBeneficiary:
          "80 municipalities in Region X",
          tappedXUPersonnel: "Itchon, Gina (CGH), Masgon, Meiyoshi (formerly SuSan), Lo, Dexter (SD-ISE), Ortiz, Edwin (COE), Pulido, Victoria Melissa (SD-SLP), Baliwag, Therese (SD-ISE)",
          statusRemarks: "ongoing",
      },
      {
        leadUnit: "CGH",
        projectNo: "3",
        projectTitle: "M3 Mangrove Mapping in Macajalar Bay",
        startDate: "January 2018",
        endDate: "June 2019",
        amount: "3,251,828.80",
        partnerFunder: "Forest Foundation Philippines, Philippine Tropical Forest Conservation Foundation, Inc",
        principalProponent: "Mars P. Tan, SJ",
        projectBeneficiary:
          "Municipalities within Macajalar Bay",
          tappedXUPersonnel: "See list of personnel",
          statusRemarks: "completed",
      },
      {
        leadUnit: "GLI",
        projectNo: "4",
        projectTitle: "Immersed, Engaged, Results Driven: Angat Buhay Leadership Training and Fellowship Journey",
        startDate: "April 2017",
        endDate: "March 2019",
        amount: "Initial Fund: 544,500.00, Addtl Fund 2019: 339,480.00",
        partnerFunder: "Seaoil Foundation",
        principalProponent: "pending information",
        projectBeneficiary:
          "6 LGUs: -Manolo Fortich, Bukidnon  -Sumilao, Bukidnon -Lantapan, Bukidnon -Kauswagan, Lanao del Norte -Tampakan, South Cotabato -Siayan, Zamboanga del Norte",
          tappedXUPersonnel: "pending information",
          statusRemarks: "completed",
      },
      {
        leadUnit: "GLI",
        projectNo: "5",
        projectTitle: "SK Mandatory Training for LGUs",
        startDate: "May 2018",
        endDate: "May 2018",
        amount: "1,883,600.00",
        partnerFunder: "DILG",
        principalProponent: "GLI",
        projectBeneficiary:
          "CDO: 80 barangays, Baungon: 16 barangays, Malitbog: 11 barangays, Talakag: 29 barangays",
          tappedXUPersonnel: "pending information",
          statusRemarks: "completed Note: Culled-out data from GLI reports",
      },
      {
        leadUnit: "MMC",
        projectNo: "6",
        projectTitle: "Mangrove Rehabilitation and Nursery Management in Macajalar Bay",
        startDate: "January 2020",
        endDate: "December 2021",
        amount: "4,746,328.40",
        partnerFunder: "Forest Foundation Philippines",
        principalProponent: "Mars P. Tan, SJ",
        projectBeneficiary:
          "Municipalities within Macajalar Bay",
          tappedXUPersonnel: "n/a",
          statusRemarks: "ongoing",
      },
      {
        leadUnit: "MMC",
        projectNo: "7",
        projectTitle: "Project Partnership with Oceanus on Mangrove Restoration",
        startDate: "April 2021",
        endDate: "December 2021",
        amount: "pending information",
        partnerFunder: "Oceanus Conservation Inc",
        principalProponent: "Astrid Sinco",
        projectBeneficiary:
          "Macajalar Bay, Salay, Misamis Oriental",
          tappedXUPersonnel: "pending information",
          statusRemarks: "ongoing",
      },
      {
        leadUnit: "CGH",
        projectNo: "8",
        projectTitle: "The Pattern of Non-Communicable Disease Risk Factors in the Province of Misamis Oriental",
        startDate: "Target date: April 2021",
        endDate: "6 months duration",
        amount: "2,900,000.00",
        partnerFunder: "DOST-Region X, DOH Center for Health Development - Northern Mindanao",
        principalProponent: "Gina S. Itchon",
        projectBeneficiary:
          "Northern Mindanao, DOH CHD-NorthMin",
          tappedXUPersonnel: "TBD",
          statusRemarks: "implementation postponed (pending local COVID situation)",
      },
    ];

    export default northminprojects;
    