const cdoprojects = [
  {
    leadUnit: "SD-ISE",
    projectNo: "1",
    projectTitle: "Philippine Resilience of Schools to Multi-Hazard",
    startDate: "February 2017",
    endDate: "February 2019",
    amount: "c/o external partner",
    partnerFunder: "De La Salle University, University College London",
    principalProponent: "Dexter S. Lo",
    projectBeneficiary:
      "DepEd identified Public Schools as evacuation centers: -City Central School, South CCS, West CCS, Kauswagan CS, Bugo CS, Bulua CS, North CCS, East CCS, Lumbia CS, Balulang ES, Macasandig ES, Bulao ES, Bayabas ES, Consolacion ES, FS Catanico ES",
    tappedXUPersonnel: "pending information",
    statusRemarks: "completed in collaboration with XUERC",
  },
  {
    leadUnit: "AEC",
    projectNo: "2",
    projectTitle: "2018 Night School Program",
    startDate: "January 2018",
    endDate: "December 2020",
    amount: "190,000.00",
    partnerFunder: "City Social Welfare and Development Department",
    principalProponent: "Maria Victoria B Trinidad, Jerome Torres",
    projectBeneficiary:
    "pending information",
    tappedXUPersonnel: "pending information",
    statusRemarks: "ongoing",
  },
  {
    leadUnit: "ERC",
    projectNo: "3",
    projectTitle: "Geotagging of Project Affected Units along the CdeO Dike System",
    startDate: "August 2017",
    endDate: "September 2017",
    amount: "30,000.00",
    partnerFunder: "RIMCU",
    principalProponent: "Jolou Miraflor",
    projectBeneficiary:
    "JICA",
    tappedXUPersonnel: "pending information",
    statusRemarks: "completed",
  },
  {
    leadUnit: "GLI (turned over to CGH 2020)",
    projectNo: "4",
    projectTitle: "Integrated Water, Sanitation and Hygiene (iWASH) Hub for the Implementation of SAgana at LIgtas na Tubig Para sa Lahat (SALINTUBIG) Project",
    startDate: "September 2017",
    endDate: "2022",
    amount: "UNDP: Php 349,280.00, DILG (SALINTUBIG):Php 2,274,000.00",
    partnerFunder: "DILG-Region X, Cagayan de Oro Water District, Malaybalay City Water District, Safer River Life Saver Foundation, Inc, Seway Inc, Group Foundation",
    principalProponent: "Gina S. Itchon",
    projectBeneficiary:
    "80 municipalities in Region X",
    tappedXUPersonnel: "Itchon, Gina (CGH), Masgon, Meiyoshi (formerly SuSan), Lo, Dexter (SD-ISE), Ortiz, Edwin (COE), Pulido, Victoria Melissa (SD-SLP), Baliwag, Therese (SD-ISE)",
    statusRemarks: "ongoing",
  },
  {
    leadUnit: "MFAD",
    projectNo: "5",
    projectTitle: "ICT-aided Community-based High Value Vegetable Extension Service",
    startDate: "April 2018",
    endDate: "pending information",
    amount: "10,000,000.00",
    partnerFunder: "CHED ",
    principalProponent: "pending information",
    projectBeneficiary:
    "pending information",
    tappedXUPersonnel: "pending information",
    statusRemarks: "pending information",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "6",
    projectTitle: "Acess to Sustainable Energy in the Philippines - Clean Energy Living Laboratories (ASEP-CELLs) Mindanao Hub",
    startDate: "January 2019",
    endDate: "December 2021",
    amount: "417,495.60 euros",
    partnerFunder: "European Union (Contracting Party) thru Ateneo de Manila University ",
    principalProponent: "Rogelio Golez Jr",
    projectBeneficiary:
    "Northern Mindanao: Academes, Electric Distributors, Cagayan de Oro LGU",
    tappedXUPersonnel: "Golez, Rogelio (COE), Obedencio, Marichu (CAS), Vallente, Jefferson Jr (COE), Villanueva, Lolit (COE), Sabal, Jhon Louie (CAS), Ventura, James Edgard Alain (CAS)",
    statusRemarks: "ongoing",
  },
  {
    leadUnit: "AEC",
    projectNo: "7",
    projectTitle: "Lamdag of ACT Project (Acceptance of Children towards Transformation)",
    startDate: "January 2019",
    endDate: "December 2019",
    amount: "20,000.00 seed money",
    partnerFunder: "City Social Welfare and Development, Ayala Foundation",
    principalProponent: "Maria Victoria B Trinidad",
    projectBeneficiary:
    "60 learners",
    tappedXUPersonnel: "pending information",
    statusRemarks: "pending information",
  },
  {
    leadUnit: "AEC",
    projectNo: "8",
    projectTitle: "Philippine Youth Leadership Program",
    startDate: "June 2018",
    endDate: "pending information",
    amount: "pending information",
    partnerFunder: "Northern Illinois University (NIU), US Department of State, US Embassy (Manila)",
    principalProponent: "Maria Victoria B Trinidad",
    projectBeneficiary:
    "pending information",
    tappedXUPersonnel: "pending information",
    statusRemarks: "pending information",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "9",
    projectTitle: "Co-hosting of the 3rd Philippine Environmental Summit",
    startDate: "February 2020",
    endDate: "February 2020",
    amount: "n/a",
    partnerFunder: "Green Convergence for Safe Food, Healthy Environment and Sustainable Economy",
    principalProponent: "Dexter S. Lo",
    projectBeneficiary:
    "Participants c/o External partner. Open for registration to: -HEIs -LGUs -Government Line Agencies -Private Sector/NGOs",
    tappedXUPersonnel: "Bagares, Rengie (COE), Capillan, Mary Globien (XCCA), Garcia, Gertrude (CAS-Biology), Gonzales, Denisse (NSTP), Gualberto, Xyla Mercedita (XSF), Jumalon, Norinyl (NSTP), Lo, Dexter S (SD-ISE), Masgon, Meiyoshi (SuSan), Ravanera, Roel R (SD), Sinco, Astrid (MMC), Tan, Mars SJ (MMC), Tarongoy, Faustino Jr (CAS-Chem), Trinidad, Maria VictoriaB (SOE-AEC)",
    statusRemarks: "completed",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "10",
    projectTitle: "Leadership for Resilient LGUs",
    startDate: "November 2019",
    endDate: "November 2022",
    amount: "n/a",
    partnerFunder: "National Resilience Council, Cagayan de Oro City LGU",
    principalProponent: "S&T: Dexter S. Lo, L&G: Gail de la Rita",
    projectBeneficiary:
    "Cagayan de Oro City LGU",
    tappedXUPersonnel: "Core:  de la Rita, Gail (SD), Lo, Dexter (SD-ISE), Vallente, Jefferson Jr (COE), Pagapulaan, Manilee Lorraine-2019 (CAS)*, Neri, Ernesto-2020 (XUCLA)** ||  Addition to the CADRE Team: Arquiza, JC Vincent G (COE), Aying, Julemer (MindaCELLs), Baliwag, Therese (SD-ISE), Obedencio, Marichu (CAS), Paduganan, Augustini Ave (COE), Velez, Don (VPHE, CAS-Socio)",
    statusRemarks: "ongoing",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "11",
    projectTitle: "Benita and Catalina Yap Foundation Awards Program",
    startDate: "August 2019",
    endDate: "July 2020",
    amount: "n/a",
    partnerFunder: "Benita and Catalina Yap Foundation",
    principalProponent: "SDO pending information",
    projectBeneficiary:
    "pending information no AAF",
    tappedXUPersonnel: "pending information no AAF",
    statusRemarks: "completed",
  },
  {
    leadUnit: "ERC",
    projectNo: "12",
    projectTitle: "Transportation and Environment Engineering Team Research Application (Transportation Planning Software)",
    startDate: "November 2019",
    endDate: "April 2022",
    amount: "n/a",
    partnerFunder: "Cagayan de Oro City LGU",
    principalProponent: "Anabel A. Abuzo",
    projectBeneficiary:
    "Cagayan de Oro City LGU",
    tappedXUPersonnel: "Abuzo, Anabel (COE), Vallente, Jefferson Jr (COE)",
    statusRemarks: "ongoing",
  },
  {
    leadUnit: "ERC",
    projectNo: "13",
    projectTitle: "Traffic Impact Assessment of Bayview Heights Phase 1 & 2",
    startDate: "June 2019",
    endDate: "July 2019",
    amount: "200,299.00",
    partnerFunder: "Alveo Land Corporation",
    principalProponent: "Anabel A. Abuzo",
    projectBeneficiary:
    "Alveo Land Corporation",
    tappedXUPersonnel: "Abuzo, Anabel (COE), Arquiza, JC Vincent (COE), Quiogue, Emmanuel Nikko (COE), Flores, Carlo (COE), Paduganan, Augustini Ave (COE), Timbal, Johan (COE-Lab), Vallente, Jefferson Jr (COE)",
    statusRemarks: "completed",
  },
  {
    leadUnit: "MMC",
    projectNo: "14",
    projectTitle: "Coastal Resource Assessment and Marine Debris Monitoring (COReMar)",
    startDate: "March 2019",
    endDate: "October 2019",
    amount: "1,441,000.00",
    partnerFunder: "Pilipinas Shell Foundation, Inc",
    principalProponent: "Mars P. Tan, SJ",
    projectBeneficiary:
    "Brgy Bayabas, CDO, Brgy Gusa, CDO, Brgy Macabalan, CDO",
    tappedXUPersonnel: "See list of personnel",
    statusRemarks: "completed",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "15",
    projectTitle: "Web-based Geospatial Risk Database for COVID-19 Pandemic Response and Recovery for KASAGANA KA Cooperative and Peace and Equity Foundation",
    startDate: "February 2021",
    endDate: "March 2021",
    amount: "588,000.00",
    partnerFunder: "Lead: National Resilience Council, Manila Observatory, Peace and Equity Foundation",
    principalProponent: "Dexter S. Lo",
    projectBeneficiary:
    "Peace and Equity Foundation (training participants), Kabuhayan sa Ganap na Kasarinlan Credit & Savings Cooperative (KASAGANA KA Coop/KCoop) -Central, East, South, and North Sectors",
    tappedXUPersonnel: "Training Team: Itchon, Gina S (JPRSM/CGH), Lo, Dexter (SD-ISE), Paduganan, Augustini Ave O (COE), Seranilla, Bonn Kleifford (COE), Vallente, Jefferson Jr (COE),  Admin: Baliwag, Therese (SD-ISE), Training Manual: Arquiza, JCVincent (COE)",
    statusRemarks: "completed",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "16",
    projectTitle: "Comprehensive Database of Externally-funded Projects and Other Projects and Activities in Xavier University through its Social Development - Institutional Societal Engagement (SD-ISE) Program from 2017-2020",
    startDate: "August 2020",
    endDate: "January 2021 *extended to August 2021",
    amount: "120,000.00",
    partnerFunder: "Dexter Lo",
    principalProponent: "Roel R. Ravanera",
    projectBeneficiary:
    "XU Social Development Office",
    tappedXUPersonnel: "Baliwag, Therese (SD-ISE)",
    statusRemarks: "Ongoing *No admin fee",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "17",
    projectTitle: "Business Area Service Recovery Plan for Cagayan de Oro",
    startDate: "July 2020",
    endDate: "September 2020",
    amount: "c/o external partner",
    partnerFunder: "USAID SURGE, Cagayan de Oro City LGU",
    principalProponent: "Dexter S. Lo",
    projectBeneficiary:
    "Cagayan de Oro City LGU",
    tappedXUPersonnel: "Arquiza, Jan Carlos Vincent G (COE), Baliwag, Therese (SD-ISE), Lo, Dexter (SD-ISE), Sabal, Jhon Louie (CAS), Vallente, Jefferson Jr (COE for GIS)",
    statusRemarks: "completed",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "18",
    projectTitle: "Web-based Geospatial Risk Database for COVID-19 Pandemic Response and Recovery Training Program - Phase 1",
    startDate: "June 1, 2020",
    endDate: "June 31, 2020",
    amount: "360,000.00",
    partnerFunder: "Lead: National Resilience Council, Coastal Cities at Risk in the Philippines, Epimetrics Inc",
    principalProponent: "Dexter S. Lo",
    projectBeneficiary:
    "6 LGUs: -Cagayan de Oro, Muntinlupa, Naga, Ormoc, Iloilo, Zamboanga || 6 Universities (Academic Partners): -Xavier University, Pamantasan ng Lungsod ng Maynila, Ateneo de Naga University, Visayas State University, UP - Visayas, Ateneo de Zamboanga University",
    tappedXUPersonnel: "Training Team: Itchon, Gina S (JPRSM/CGH), Lo, Dexter (SD-ISE), Paduganan, Augustini Ave O (COE), Vallente, Jefferson Jr (COE) || Admin: Baliwag, Therese (SD-ISE)",
    statusRemarks: "completed",
  },
  {
    leadUnit: "SD-ISE",
    projectNo: "19",
    projectTitle: "Web-based Geospatial Risk Database for COVID-19 Pandemic Response and Recovery Training Program - Phase 2",
    startDate: "July 2020",
    endDate: "September 2020",
    amount: "265,500.00",
    partnerFunder: "Lead: National Resilience Council, Coastal Cities at Risk in the Philippines, Epimetrics Inc",
    principalProponent: "Dexter S. Lo",
    projectBeneficiary:
    "6 LGUs: -Cagayan de Oro, Muntinlupa, Naga, Ormoc, Iloilo, Zamboanga || 6 Universities (Academic Partners): -Xavier University, Pamantasan ng Lungsod ng Maynila, Ateneo de Naga University, Visayas State University, UP - Visayas, Ateneo de Zamboanga University",
    tappedXUPersonnel: "Training Team: Itchon, Gina S (JPRSM/CGH), Lo, Dexter (SD-ISE), Paduganan, Augustini Ave O (COE), Vallente, Jefferson Jr (COE) || Admin: Baliwag, Therese (SD-ISE)",
    statusRemarks: "completed",
  },
  {
    leadUnit: "AEC",
    projectNo: "20",
    projectTitle: "2020 Night School Program",
    startDate: "pending information",
    endDate: "pending information",
    amount: "190,000.00",
    partnerFunder: "City Social Welfare and Development Department",
    principalProponent: "Maria Victoria B Trinidad/Jerome Torres",
    projectBeneficiary:
    "pending information",
    tappedXUPersonnel: "pending information",
    statusRemarks: "ongoing",
  },
  {
    leadUnit: "XCHMR",
    projectNo: "21",
    projectTitle: "Mental Health and Wellness in the Workplace: Mindfulness and Distress Tolerance",
    startDate: "October 2020",
    endDate: "TBD pending COVID restrictions",
    amount: "80,000.00",
    partnerFunder: "Nestle Philippines Inc-CDO Factory",
    principalProponent: "Yayetta de la Pena",
    projectBeneficiary:
    "Nestle Philippienes-CDO employees (20 pax)",
    tappedXUPersonnel: "pending information",
    statusRemarks: "pending information",
  },
  {
    leadUnit: "XCHMR",
    projectNo: "22",
    projectTitle: "Mental Health and Well-Being at Work: Essence and Legislation, and Assessment of Mental Health Needs",
    startDate: "March 2021",
    endDate: "TBD pending COVID restrictions",
    amount: "94,445.00",
    partnerFunder: "Pilipinas Kao, Inc",
    principalProponent: "Yayetta de la Pena",
    projectBeneficiary:
    "Pilipinas Kao Inc employees (43 pax)",
    tappedXUPersonnel: "pending information",
    statusRemarks: "completed",
  },
  {
    leadUnit: "XCHMR",
    projectNo: "23",
    projectTitle: "Online One-on-one Counseling cum Psychosocial Processing Services for Del Monte Philipppines, Inc",
    startDate: "for clarification",
    endDate: "for clarification",
    amount: "for clarification",
    partnerFunder: "for clarification",
    principalProponent: " for clarification",
    projectBeneficiary:
    "for clarification",
    tappedXUPersonnel: "for clarification",
    statusRemarks: "for clarification",
  },
  {
    leadUnit: "XUCLA",
    projectNo: "24",
    projectTitle: "International Pro Bono Alliance Legal Aid Referreal Network",
    startDate: "June 2021",
    endDate: "until revoked",
    amount: "n/a",
    partnerFunder: "International Pro Bono Alliance",
    principalProponent: "Ernesto B. Neri",
    projectBeneficiary:
    "pending information",
    tappedXUPersonnel: "n/a",
    statusRemarks: "ongoing",
  },
  {
    leadUnit: "SDO",
    projectNo: "25",
    projectTitle: "Project OWKCi: Online Wellness Kontra COVID initiative",
    startDate: "pending information",
    endDate: "pending information",
    amount: "c/o external partner",
    partnerFunder: "Cagayan de Oro City LGU",
    principalProponent: "SDO",
    projectBeneficiary:
    "Cagayan de Oro City LGU",
    tappedXUPersonnel: "XCHMR, OMM, GCO",
    statusRemarks: "pending information Note: No archive copy pf signed MOU/AAF",
  },
];


export default cdoprojects;
